### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by agdestine**

### CODE REVIEW

**Comment by agdestine** [comment]
Updated

**Comment by bbengfort** [comment]
@agdestine -- thank you for submitting a pull request! I haven't taken a look at your work quite yet, but I was hoping that you could move the notebook from the `notebooks` folder to a folder in `examples` -- `examples/agdestine` --> this will allow us to organize the code better and give you attribution for your work!

**Comment by bbengfort** [comment]
@agdestine - did you still want me to add your work to the main repo in examples?

**Comment by agdestine** [comment]
@bbengfort I cannot create folders (agdestine, agdestine/data, agdestine/notebook) inside the examples directory.

**Comment by bbengfort** [comment]
@agdestine you can - if you clone the repository to your local machine, make edits then push back to GitHub; or you can simply type in the file name as agdestine/myfile.txt and it will automatically create the directory for you as you're typing it. Just be careful, the editing can be tricky if you hit backspace when doing that.

**Comment by agdestine** [comment]
@bbengfort Thanks for the advise.

**Pull request closed without merging**
