### PR TITLE
createing PR for my workshop Notebook 

### PR DESCRIPTION
**Pull request by edeo**
Here is my jupyter notebook for the ML class workshop. Let me what parts to clean up, or to change. thanks!

### CODE REVIEW

**Comment by bbengfort** [comment]
@edeo perfect, thanks! We're at PyCon right now, so if you don't hear from us make sure you ping me to review your PR.

**Comment by edeo** [comment]
Hi Ben,

I hope alls well.  Is there anything I should do to fix up my code for the pull request? Thanks!

**Comment by bbengfort** [comment]
@edeo whoops - no sorry, I'll go ahead and merge. Did you have any questions from your example? I haven't had the time to review it.

**Comment by edeo** [comment]
@bbengfort - no real big questions, if you have any advice on how to make it look more professional / better from a software engineering sense, or any advice really  please let me know. thanks!

**Pull request merged**
